version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=sqlite:./E_commerce.db
      - SOLR_URL=http://solr:8983/solr/products/select
    depends_on:
      solr:
        condition: service_healthy
    networks:
      - ecommerce-net
    restart: unless-stopped

  solr:
    image: solr:9.3
    container_name: solr
    ports:
      - "8983:8983"
    volumes:
      - ./solr:/var/solr
    command: |
      solr-precreate products
    networks:
      - ecommerce-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/admin/info/system"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  solr-data:

networks:
  ecommerce-net:
    driver: bridge
